// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBlR5xEpFcJSBk8xyFFGK3u_S0JBn8SG8',
    appId: '1:807317377019:web:4af2d6b975302c7fa2455e',
    messagingSenderId: '807317377019',
    projectId: 'myapp-bd595',
    authDomain: 'myapp-bd595.firebaseapp.com',
    storageBucket: 'myapp-bd595.appspot.com',
    measurementId: 'G-SK9WYZ5WS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVpugodO0nRvPFk9zmzjRSljyywq7Mukw',
    appId: '1:807317377019:android:4317085d546ee0daa2455e',
    messagingSenderId: '807317377019',
    projectId: 'myapp-bd595',
    storageBucket: 'myapp-bd595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRzJD8fV3B45jt7FpE5X7kSjc0919qta8',
    appId: '1:807317377019:ios:446bab09f81edd17a2455e',
    messagingSenderId: '807317377019',
    projectId: 'myapp-bd595',
    storageBucket: 'myapp-bd595.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRzJD8fV3B45jt7FpE5X7kSjc0919qta8',
    appId: '1:807317377019:ios:446bab09f81edd17a2455e',
    messagingSenderId: '807317377019',
    projectId: 'myapp-bd595',
    storageBucket: 'myapp-bd595.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBlR5xEpFcJSBk8xyFFGK3u_S0JBn8SG8',
    appId: '1:807317377019:web:6e8720b6cd44c65ca2455e',
    messagingSenderId: '807317377019',
    projectId: 'myapp-bd595',
    authDomain: 'myapp-bd595.firebaseapp.com',
    storageBucket: 'myapp-bd595.appspot.com',
    measurementId: 'G-F8M7CBQFMD',
  );
}
